<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/><style>
  body{font-family:Arial,sans-serif;font-size:14px;color:#333;}
  .header{background:#171532;color:#fff;padding:20px 30px;text-align:center;}
  .ref{font-size:28px;font-weight:900;letter-spacing:2px;margin:8px 0;}
  .row{display:flex;justify-content:space-between;padding:10px 30px;border-bottom:1px solid #f0f0f0;}
  .label{color:#9ca3af;font-size:12px;}
  .value{font-weight:600;}
  .pay-row{display:flex;justify-content:space-between;padding:8px 30px;}
  .footer{background:#f9fafb;padding:15px 30px;text-align:center;font-size:12px;color:#9ca3af;}
</style></head>
<body>
  <div class="header">
    <div style="font-size:22px;font-weight:900;margin-bottom:4px;">MyRoom</div>
    <div style="opacity:.8;font-size:13px;">Hourly Hotel Booking · India</div>
  </div>
  <div style="background:#fff;padding:20px 30px;text-align:center;border-bottom:2px solid #5B5BD6;">
    <div style="color:#9ca3af;font-size:11px;letter-spacing:2px;text-transform:uppercase;">Booking Confirmation</div>
    <div class="ref">{{ $booking->booking_ref }}</div>
    <div style="background:#d1fae5;color:#065f46;display:inline-block;padding:4px 16px;border-radius:20px;font-size:12px;font-weight:700;">{{ $booking->status_label }}</div>
  </div>
  @foreach(['Guest'=>$booking->guest_name,'Mobile'=>$booking->guest_phone,'Email'=>$booking->guest_email??'—','Hotel'=>$booking->hotel->name,'Location'=>$booking->hotel->address,'Room'=>$booking->room->name,'Stay Type'=>ucfirst($booking->stay_type).($booking->stay_type==='hourly'?' ('.$booking->hours.' hrs)':''),'Check-in'=>$booking->checkin_at->format('d M Y, h:i A'),'Check-out'=>($booking->checkout_at?->format('d M Y, h:i A')??'—')] as $l=>$v)
    <div class="row"><span class="label">{{ $l }}</span><span class="value">{{ $v }}</span></div>
  @endforeach
  <div style="background:#f9fafb;padding:15px 30px;margin:10px 0;">
    <div style="font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#9ca3af;margin-bottom:10px;">Payment Summary</div>
    <div class="pay-row"><span>Room Rate</span><span>₹{{ number_format($booking->room_rate) }}</span></div>
    @if($booking->discount_amount>0)<div class="pay-row" style="color:green;"><span>Discount</span><span>-₹{{ number_format($booking->discount_amount) }}</span></div>@endif
    <div class="pay-row" style="color:green;font-weight:700;"><span>Paid Online</span><span>₹{{ number_format($booking->advance_amount) }}</span></div>
    <div class="pay-row" style="font-weight:700;font-size:16px;border-top:1px solid #e5e7eb;padding-top:10px;"><span>Pay at Hotel</span><span style="color:#5B5BD6;">₹{{ number_format($booking->balance_amount) }}</span></div>
  </div>
  <div class="footer">Generated by MyRoom · support@myroom.in · myroom.in · This is an electronically generated receipt.</div>
</body>
</html>
